package com.andika.project_credit_scoring

object Constanst {
    val MENU_HOME = "Home"
    val MENU_TRANSACTION = "Transaction"
    val MENU_HISTORY = "History"
    val MENU_ACCOUNT = "Account"

    // URL
    val BASE_URL = "http://10.10.12.251:8080/"

    // SHARED PREFERENCES TAG
    val TOKEN = "TOKEN"
    val USERNAME = "USERNAME"
    val PASSWORD = "PASSWORD"
    val PREREFERENCES = "PREFERENCES"

    val VALIDATION_EMAIL = "VALIDATION_EMAIL"
    val VALIDATION_PASSWORD = "VALIDATION_EMAIL"
    val VALIDATION_CONFIRM_PASSWORD = "VALIDATION_CONFIRM_PASSWORD"
    val VALIDATION_USERNAME = "VALIDATION_USERNAME"
    val VALIDATION_SUCCESS = "VALIDATION_SUCCESS"

}